### ISSUE TITLE
Online scraper doesn't work

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#13]
Installed the latest version today, now i can no longer add new rom using online scraper, here's the error : 
```
18:04:06 T:140340406695680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'local_title' is not defined
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 217, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1448, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 4399, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 4611, in _roms_process_scanned_ROM
                                                selected_title     = self._roms_process_asset_policy_2(ASSET_TITLE, local_title, ROM, launcher)
                                            NameError: global name 'local_title' is not defined
                                            -->End of Python script error report<--
```

Edit : did a little more testing 

-gamedb metadata scraper work, but with some roms it failed with this error

```
23:53:35 T:140391097542400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'VLAUNCHER_FAV_ID' is not defined
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 220, in run_plugin
                                                self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1498, in _command_edit_rom
                                                if not self._gui_scrap_rom_metadata(roms, romID, launcherID): return
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 4987, in _gui_scrap_rom_metadata
                                                if launcherID == VLAUNCHER_FAV_ID:
                                            NameError: global name 'VLAUNCHER_FAV_ID' is not defined
                                            -->End of Python script error report<--
```

-gamedb asset scraper failed
-gamefaq metadata scraper failed
-gamefaq asset scraper failed

**Comment by Wintermute0110** [comment]
Still working with the scraper. Current scraper does not differentiate yet all the new kinds of artwork. Will take me some time to fix it.

**Comment by Wintermute0110** [comment]
Scraper should be working now. Keep in mind scraper itself is not very accurate at the moment.

**Comment by mac1202** [comment]
gamedb scraper is working now, bu gamefaq one still failed wirh this error : 

```
11:17:15 T:140311137347328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'title',)
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 221, in run_plugin
                                                self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1498, in _command_edit_rom
                                                if not self._gui_scrap_rom_metadata(roms, romID, launcherID): return
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 4815, in _gui_scrap_rom_metadata
                                                gamedata = self.scraper_metadata.get_metadata(results[selectgame])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/scrap_metadata.py", line 255, in get_metadata
                                                gamedata['title'] = game['title']
                                            KeyError: (u'title',)
                                            -->End of Python script error report<--

```

**Comment by Wintermute0110** [comment]
GameFAQs scraper should be working now :).

**Comment by mac1202** [comment]
I close this one both seems to work now.
