### ISSUE TITLE
Action on kodi playing media doesnt work.

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#9]
Hello whenever action I choose for this option the media continue to play.

**Comment by Wintermute0110** [comment]
Hi, should be fixed now. Also, AEL should be much faster now returning after you close the launched program when no media is playing. I have tested the patch in Linux but please tell me if it does not work to you.

**Comment by mac1202** [comment]
Now whenever setting I choose it stop the media wich is fine for me as this the setting I use. But I let the issue open for the moment as other may want to use "let s play" or "pause"

**Comment by Wintermute0110** [comment]
Please go to settings, advanced (I think...) and set debug level to DEBUG. Post log so I can have a look.

**Comment by mac1202** [comment]
Here s the debug log 
`18:39:14 T:139846201382976   DEBUG: Previous line repeats 436 times.
18:39:14 T:139846201382976   DEBUG: LIRC: Update - NEW at 23589:000000037ff07bdd 00 KEY_OK mceusb (KEY_OK)
18:39:14 T:139846201382976   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
18:39:14 T:139846201382976   DEBUG: StartScript - calling plugin Super Favourites('plugin://plugin.program.super.favourites/','10','?label=Legend+of+Zelda%3A+Twilight+Princess%2C+The&mode=600&cmd=PlayMedia%28%22plugin%3A%2F%2Fplugin.program.advanced.emulator.launcher%2F%3Fcom%3DLAUNCH_ROM%26catID%3Dfca2b6b98f5b18a31da7de324feb5a22%26launID%3D512cc5146b36e0561efa0e11dc94c4a4%26romID%3Df7d5000374ca4bfdb3c6d8686ce4b4cc%26sf_options%3Dfanart%253D%252Fhome%252Fmac%252FJeux%252FRoms%252FSystem%252FArtwork%252Fgamecube%252FLegend%2Bof%2BZelda%252C%2BThe%2B-%2BTwilight%2BPrincess%2B%2528Europe%2529%2B%2528En%252CFr%252CDe%252CEs%252CIt%2529_fanart.jpg%2526winID%253D10000%2526desc%253DIn%2Bthe%2Bnext%2Bchapter%2Bin%2Bthe%2BLegend%2Bof%2BZelda%2Bseries%252C%2BLink%2Bcan%2Btransform%2Binto%2Ba%2Bwolf%2Bto%2Bscour%2Bthe%2Bdarkened%2Bland%2Bof%2BHyrule.%2BWith%2Bthe%2Bhelp%2Bof%2BMidna%252C%2Ba%2Bmysterious%2Bbeing%252C%2Byou%2Bmust%2Bguide%2BLink%2Bthrough%2Bhordes%2Bof%2Bfoul%2Bcreatures%2Band%2Bchallenging%2Bbosses%2Busing%2Bnew%2Bmoves%2Band%2Ba%2Bnew%2Bhorseback%2Bcombat%2Bsystem.%2B%2BMany%2Bpuzzles%2Bstand%2Bbetween%2BLink%2Band%2Bthe%2Bfulfillment%2Bof%2Bhis%2Bquest%252C%2Bso%2Byou%2Bmust%2Bsharpen%2Byour%2Bwits%2Bas%2Byou%2Bhunt%2Bfor%2Bweapons%2Band%2Bitems.%2526_options_sf%22%29&image=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_thumb.jpg&fanart=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg')
18:39:14 T:139843057940224   DEBUG: Thread LanguageInvoker start, auto delete: false
18:39:14 T:139843057940224    INFO: initializing python engine.
18:39:14 T:139843057940224   DEBUG: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): start processing
18:39:14 T:139843057940224   DEBUG: -->Python Interpreter Initialized<--
18:39:14 T:139843057940224   DEBUG: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): the source file to load is "/home/mac/.kodi/addons/plugin.program.super.favourites/default.py"
18:39:14 T:139843057940224   DEBUG: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): setting the Python path to /home/mac/.kodi/addons/plugin.program.super.favourites:/home/mac/.kodi/addons/script.module.addon.common/lib:/home/mac/.kodi/addons/script.module.metahandler/lib:/home/mac/.kodi/addons/script.module.myconnpy/lib:/home/mac/.kodi/addons/script.module.simplejson/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0:/usr/lib/python2.7/site-packages/wx-3.0-gtk2
18:39:14 T:139843057940224   DEBUG: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): entering source directory /home/mac/.kodi/addons/plugin.program.super.favourites
18:39:14 T:139843057940224   DEBUG: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): instantiating addon using automatically obtained id of "plugin.program.super.favourites" dependent on version 2.1.0 of the xbmc.python api
18:39:14 T:139845316429568   DEBUG: Thread scriptobs start, auto delete: false
18:39:14 T:139846201382976   DEBUG: ------ Window Init (DialogBusy.xml) ------
18:39:14 T:139846201382976   DEBUG: Window DialogBusy.xml was already loaded
18:39:14 T:139846201382976   DEBUG: Alloc resources: 0.01ms
18:39:14 T:139846201382976   DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.
18:39:14 T:139843049547520   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 1
18:39:14 T:139846201382976   DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.
18:39:15 T:139843049547520   DEBUG: Previous line repeats 3 times.
18:39:15 T:139843049547520   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 1
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : ------------------ Launch Parameters ------------------
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : ?label=Legend+of+Zelda%3A+Twilight+Princess%2C+The&mode=600&cmd=PlayMedia%28%22plugin%3A%2F%2Fplugin.program.advanced.emulator.launcher%2F%3Fcom%3DLAUNCH_ROM%26catID%3Dfca2b6b98f5b18a31da7de324feb5a22%26launID%3D512cc5146b36e0561efa0e11dc94c4a4%26romID%3Df7d5000374ca4bfdb3c6d8686ce4b4cc%26sf_options%3Dfanart%253D%252Fhome%252Fmac%252FJeux%252FRoms%252FSystem%252FArtwork%252Fgamecube%252FLegend%2Bof%2BZelda%252C%2BThe%2B-%2BTwilight%2BPrincess%2B%2528Europe%2529%2B%2528En%252CFr%252CDe%252CEs%252CIt%2529_fanart.jpg%2526winID%253D10000%2526desc%253DIn%2Bthe%2Bnext%2Bchapter%2Bin%2Bthe%2BLegend%2Bof%2BZelda%2Bseries%252C%2BLink%2Bcan%2Btransform%2Binto%2Ba%2Bwolf%2Bto%2Bscour%2Bthe%2Bdarkened%2Bland%2Bof%2BHyrule.%2BWith%2Bthe%2Bhelp%2Bof%2BMidna%252C%2Ba%2Bmysterious%2Bbeing%252C%2Byou%2Bmust%2Bguide%2BLink%2Bthrough%2Bhordes%2Bof%2Bfoul%2Bcreatures%2Band%2Bchallenging%2Bbosses%2Busing%2Bnew%2Bmoves%2Band%2Ba%2Bnew%2Bhorseback%2Bcombat%2Bsystem.%2B%2BMany%2Bpuzzles%2Bstand%2Bbetween%2BLink%2Band%2Bthe%2Bfulfillment%2Bof%2Bhis%2Bquest%252C%2Bso%2Byou%2Bmust%2Bsharpen%2Byour%2Bwits%2Bas%2Byou%2Bhunt%2Bfor%2Bweapons%2Band%2Bitems.%2526_options_sf%22%29&image=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_thumb.jpg&fanart=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : ['plugin://plugin.program.super.favourites/', '10', '?label=Legend+of+Zelda%3A+Twilight+Princess%2C+The&mode=600&cmd=PlayMedia%28%22plugin%3A%2F%2Fplugin.program.advanced.emulator.launcher%2F%3Fcom%3DLAUNCH_ROM%26catID%3Dfca2b6b98f5b18a31da7de324feb5a22%26launID%3D512cc5146b36e0561efa0e11dc94c4a4%26romID%3Df7d5000374ca4bfdb3c6d8686ce4b4cc%26sf_options%3Dfanart%253D%252Fhome%252Fmac%252FJeux%252FRoms%252FSystem%252FArtwork%252Fgamecube%252FLegend%2Bof%2BZelda%252C%2BThe%2B-%2BTwilight%2BPrincess%2B%2528Europe%2529%2B%2528En%252CFr%252CDe%252CEs%252CIt%2529_fanart.jpg%2526winID%253D10000%2526desc%253DIn%2Bthe%2Bnext%2Bchapter%2Bin%2Bthe%2BLegend%2Bof%2BZelda%2Bseries%252C%2BLink%2Bcan%2Btransform%2Binto%2Ba%2Bwolf%2Bto%2Bscour%2Bthe%2Bdarkened%2Bland%2Bof%2BHyrule.%2BWith%2Bthe%2Bhelp%2Bof%2BMidna%252C%2Ba%2Bmysterious%2Bbeing%252C%2Byou%2Bmust%2Bguide%2BLink%2Bthrough%2Bhordes%2Bof%2Bfoul%2Bcreatures%2Band%2Bchallenging%2Bbosses%2Busing%2Bnew%2Bmoves%2Band%2Ba%2Bnew%2Bhorseback%2Bcombat%2Bsystem.%2B%2BMany%2Bpuzzles%2Bstand%2Bbetween%2BLink%2Band%2Bthe%2Bfulfillment%2Bof%2Bhis%2Bquest%252C%2Bso%2Byou%2Bmust%2Bsharpen%2Byour%2Bwits%2Bas%2Byou%2Bhunt%2Bfor%2Bweapons%2Band%2Bitems.%2526_options_sf%22%29&image=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_thumb.jpg&fanart=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg']
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : mode        = 600
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : cmd         = PlayMedia("plugin://plugin.program.advanced.emulator.launcher/?com=LAUNCH_ROM&catID=fca2b6b98f5b18a31da7de324feb5a22&launID=512cc5146b36e0561efa0e11dc94c4a4&romID=f7d5000374ca4bfdb3c6d8686ce4b4cc&sf_options=fanart%3D%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg%26winID%3D10000%26desc%3DIn+the+next+chapter+in+the+Legend+of+Zelda+series%2C+Link+can+transform+into+a+wolf+to+scour+the+darkened+land+of+Hyrule.+With+the+help+of+Midna%2C+a+mysterious+being%2C+you+must+guide+Link+through+hordes+of+foul+creatures+and+challenging+bosses+using+new+moves+and+a+new+horseback+combat+system.++Many+puzzles+stand+between+Link+and+the+fulfillment+of+his+quest%2C+so+you+must+sharpen+your+wits+as+you+hunt+for+weapons+and+items.%26_options_sf")
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : folder      =
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : params      = {'fanart': '/home/mac/Jeux/Roms/System/Artwork/gamecube/Legend of Zelda, The - Twilight Princess (Europe) (En,Fr,De,Es,It)_fanart.jpg', 'image': '/home/mac/Jeux/Roms/System/Artwork/gamecube/Legend of Zelda, The - Twilight Princess (Europe) (En,Fr,De,Es,It)_thumb.jpg', 'cmd': 'PlayMedia("plugin://plugin.program.advanced.emulator.launcher/?com=LAUNCH_ROM&catID=fca2b6b98f5b18a31da7de324feb5a22&launID=512cc5146b36e0561efa0e11dc94c4a4&romID=f7d5000374ca4bfdb3c6d8686ce4b4cc&sf_options=fanart%3D%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg%26winID%3D10000%26desc%3DIn+the+next+chapter+in+the+Legend+of+Zelda+series%2C+Link+can+transform+into+a+wolf+to+scour+the+darkened+land+of+Hyrule.+With+the+help+of+Midna%2C+a+mysterious+being%2C+you+must+guide+Link+through+hordes+of+foul+creatures+and+challenging+bosses+using+new+moves+and+a+new+horseback+combat+system.++Many+puzzles+stand+between+Link+and+the+fulfillment+of+his+quest%2C+so+you+must+sharpen+your+wits+as+you+hunt+for+weapons+and+items.%26_options_sf")', 'mode': '600', 'label': 'Legend of Zelda: Twilight Princess, The'}
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : launchMode  =
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : contentType = movies
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : viewType    = 50
18:39:15 T:139843057940224   DEBUG: Super Favourites V1.0.43 : -------------------------------------------------------
18:39:15 T:139843057940224    INFO: CPythonInvoker(35, /home/mac/.kodi/addons/plugin.program.super.favourites/default.py): script successfully run
18:39:15 T:139845316429568   DEBUG: Thread scriptobs 139845316429568 terminating
18:39:15 T:139846201382976   DEBUG: DoWork - Saving file state for video item pvr://channels/tv/Toutes les chaînes/pvr.hts_864367120.pvr
18:39:15 T:139843057940224    INFO: Python script stopped
18:39:15 T:139843057940224   DEBUG: Thread LanguageInvoker 139843057940224 terminating
18:39:15 T:139846201382976   DEBUG: DoWork - Saving file state for dsp audio item pvr://channels/tv/Toutes les chaînes/pvr.hts_864367120.pvr
18:39:15 T:139846201382976   DEBUG: Loading settings for
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers()
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
18:39:15 T:139846201382976   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: MPV
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
18:39:15 T:139846201382976   DEBUG: CPlayerCoreFactory::GetPlayers: added 2 players
18:39:15 T:139846201382976  NOTICE: CVideoPlayer::CloseFile()
18:39:15 T:139846201382976  NOTICE: VideoPlayer: waiting for threads to exit
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 5
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:15 T:139843531175680   DEBUG: Previous line repeats 6 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: Previous line repeats 2 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 5
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:15 T:139843531175680   DEBUG: Previous line repeats 6 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:15 T:139843049547520   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843049547520 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843049547520 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:15 T:139843531175680   DEBUG: Previous line repeats 6 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 5
18:39:15 T:139843049547520 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: Previous line repeats 2 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: Previous line repeats 4 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:15 T:139843531175680   DEBUG: Previous line repeats 6 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 5
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:15 T:139843531175680   DEBUG: Previous line repeats 1 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:15 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:15 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:16 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:16 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:16 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:16 T:139843531175680   DEBUG: Previous line repeats 6 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:16 T:139843242784512   DEBUG: Previous line repeats 2 times.
18:39:16 T:139843242784512  NOTICE: CVideoPlayer::OnExit()
18:39:16 T:139843242784512  NOTICE: Closing stream player 1
18:39:16 T:139843242784512  NOTICE: Waiting for audio thread to exit
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:16 T:139843041154816  NOTICE: thread end: CVideoPlayerAudio::OnExit()
18:39:16 T:139843242784512  NOTICE: Closing audio device
18:39:16 T:139843041154816   DEBUG: Thread VideoPlayerAudio 139843041154816 terminating
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1
18:39:16 T:139843531175680   DEBUG: Previous line repeats 1 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 5
18:39:16 T:139843242784512   DEBUG: CDVDAudio::Flush - flush audio stream
18:39:16 T:139846187149056   DEBUG: CActiveAE::DiscardStream - audio stream deleted
18:39:16 T:139846187149056   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
18:39:16 T:139843242784512   DEBUG: Previous line repeats 1 times.
18:39:16 T:139843242784512  NOTICE: Deleting audio codec
18:39:16 T:139843242784512  NOTICE: Closing stream player 2
18:39:16 T:139843242784512  NOTICE: waiting for video thread to exit
18:39:16 T:139846176577280    INFO: CActiveAESink::OpenSink - initialize sink
18:39:16 T:139843049547520  NOTICE: thread end: video_thread
18:39:16 T:139843049547520   DEBUG: Thread VideoPlayerVideo 139843049547520 terminating
18:39:16 T:139843242784512  NOTICE: deleting video codec
18:39:16 T:139843242784512  NOTICE: Closing stream player 3
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 2
18:39:16 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 3
18:39:16 T:139843531175680   DEBUG: Previous line repeats 5 times.
18:39:16 T:139843531175680   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 4
18:39:16 T:139846176577280   DEBUG: Previous line repeats 6 times.
18:39:16 T:139846176577280   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:Default
18:39:16 T:139846176577280   DEBUG: PulseAudio: Context authorizing
18:39:16 T:139846176577280   DEBUG: PulseAudio: Context setting name
18:39:16 T:139846176577280   DEBUG: PulseAudio: Context ready
18:39:16 T:139844445521664   DEBUG: DoWork - Saving file state for video item pvr://channels/tv/Toutes les chaînes/pvr.hts_864367120.pvr
18:39:16 T:139843242784512   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux unsubscribe from 864367120
18:39:16 T:139843242784512   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux successfully unsubscribed from channel id 864367120, subscription id 1
18:39:16 T:139843242784512   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux close
18:39:16 T:139843242784512   DEBUG: CDVDInputStreamPVRManager::Close - stream closed
18:39:16 T:139843242784512   DEBUG: OnPlayBackStopped: play state was 2, starting 1
18:39:16 T:139843242784512   DEBUG: Thread VideoPlayer 139843242784512 terminating
18:39:16 T:139846201382976  NOTICE: VideoPlayer: finished waiting
18:39:16 T:139846201382976   DEBUG: DeleteRenderer - deleting renderer
18:39:16 T:139846201382976   DEBUG: LinuxRendererGL: Cleaning up GL resources
18:39:16 T:139846201382976  NOTICE: VideoPlayer: Opening:
18:39:16 T:139846201382976   DEBUG: LinuxRendererGL: Cleaning up GL resources
18:39:16 T:139846201382976   DEBUG: CLinuxRendererGL::PreInit - precision of luminance 16 is 16
18:39:16 T:139843242784512   DEBUG: Thread VideoPlayer start, auto delete: false
18:39:16 T:139843242784512  NOTICE: Creating InputStream
18:39:16 T:139843242784512   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/players/VideoPlayer/libdvdnav-x86_64-linux.so)
18:39:16 T:139843242784512   DEBUG: Loading: /usr/lib/kodi/system/players/VideoPlayer/libdvdnav-x86_64-linux.so
18:39:16 T:139843242784512    INFO:   msg: libdvdnav: Using dvdnav version 5.0.4
18:39:16 T:139843242784512    INFO:   msg: libdvdread: Can't stat
18:39:16 T:139843242784512    INFO:   msg: libdvdread: Could not open
18:39:16 T:139843242784512   DEBUG: libdvdnav: vm: failed to open/read the DVD
18:39:16 T:139843242784512   ERROR: Error on dvdnav_open
18:39:16 T:139843242784512   ERROR: CVideoPlayer::OpenInputStream - error opening []
18:39:16 T:139843242784512  NOTICE: CVideoPlayer::OnExit()
18:39:16 T:139843242784512   DEBUG: OnPlayBackStopped: play state was 1, starting 1
18:39:16 T:139843242784512   DEBUG: Thread VideoPlayer 139843242784512 terminating
18:39:16 T:139846201382976   DEBUG: OnPlayBackStopped: play state was 3, starting 0
18:39:16 T:139846201382976   ERROR: PlayMedia could not play media: plugin://plugin.program.super.favourites/?label=Legend+of+Zelda%3A+Twilight+Princess%2C+The&mode=600&cmd=PlayMedia%28%22plugin%3A%2F%2Fplugin.program.advanced.emulator.launcher%2F%3Fcom%3DLAUNCH_ROM%26catID%3Dfca2b6b98f5b18a31da7de324feb5a22%26launID%3D512cc5146b36e0561efa0e11dc94c4a4%26romID%3Df7d5000374ca4bfdb3c6d8686ce4b4cc%26sf_options%3Dfanart%253D%252Fhome%252Fmac%252FJeux%252FRoms%252FSystem%252FArtwork%252Fgamecube%252FLegend%2Bof%2BZelda%252C%2BThe%2B-%2BTwilight%2BPrincess%2B%2528Europe%2529%2B%2528En%252CFr%252CDe%252CEs%252CIt%2529_fanart.jpg%2526winID%253D10000%2526desc%253DIn%2Bthe%2Bnext%2Bchapter%2Bin%2Bthe%2BLegend%2Bof%2BZelda%2Bseries%252C%2BLink%2Bcan%2Btransform%2Binto%2Ba%2Bwolf%2Bto%2Bscour%2Bthe%2Bdarkened%2Bland%2Bof%2BHyrule.%2BWith%2Bthe%2Bhelp%2Bof%2BMidna%252C%2Ba%2Bmysterious%2Bbeing%252C%2Byou%2Bmust%2Bguide%2BLink%2Bthrough%2Bhordes%2Bof%2Bfoul%2Bcreatures%2Band%2Bchallenging%2Bbosses%2Busing%2Bnew%2Bmoves%2Band%2Ba%2Bnew%2Bhorseback%2Bcombat%2Bsystem.%2B%2BMany%2Bpuzzles%2Bstand%2Bbetween%2BLink%2Band%2Bthe%2Bfulfillment%2Bof%2Bhis%2Bquest%252C%2Bso%2Byou%2Bmust%2Bsharpen%2Byour%2Bwits%2Bas%2Byou%2Bhunt%2Bfor%2Bweapons%2Band%2Bitems.%2526_options_sf%22%29&image=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_thumb.jpg&fanart=%2Fhome%2Fmac%2FJeux%2FRoms%2FSystem%2FArtwork%2Fgamecube%2FLegend+of+Zelda%2C+The+-+Twilight+Princess+%28Europe%29+%28En%2CFr%2CDe%2CEs%2CIt%29_fanart.jpg
18:39:16 T:139846195541760   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
18:39:16 T:139846195541760   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
18:39:16 T:139844420343552  NOTICE: Stream All The Sources: Service: Playback Stopped
18:39:16 T:139844982392576   DEBUG: ### [Unpause Jumpback] - Cancelling alarm - playback either resumed or stopped by the user
18:39:16 T:139846201382976   DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.
18:39:16 T:139846201382976  NOTICE: CVideoPlayer::CloseFile()
18:39:16 T:139846201382976  NOTICE: VideoPlayer: waiting for threads to exit
18:39:16 T:139846201382976  NOTICE: VideoPlayer: finished waiting
18:39:16 T:139846201382976   DEBUG: DeleteRenderer - deleting renderer
18:39:16 T:139846201382976   DEBUG: LinuxRendererGL: Cleaning up GL resources
18:39:16 T:139846201382976  NOTICE: CVideoPlayer::CloseFile()
18:39:16 T:139846201382976  NOTICE: VideoPlayer: waiting for threads to exit
18:39:16 T:139846201382976  NOTICE: VideoPlayer: finished waiting
18:39:16 T:139846201382976   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
18:39:16 T:139843252225792   DEBUG: CVideoReferenceClock: Cleaning up GLX
18:39:16 T:139843252225792   DEBUG: Thread RefClock 139843252225792 terminating
18:39:16 T:139846201382976   DEBUG: StartScript - calling plugin Advanced Emulator Launcher('plugin://plugin.program.advanced.emulator.launcher/','11','?com=LAUNCH_ROM&catID=fca2b6b98f5b18a31da7de324feb5a22&launID=512cc5146b36e0561efa0e11dc94c4a4&romID=f7d5000374ca4bfdb3c6d8686ce4b4cc')
18:39:16 T:139843242784512   DEBUG: Thread LanguageInvoker start, auto delete: false
18:39:16 T:139843242784512    INFO: initializing python engine.
18:39:16 T:139843242784512   DEBUG: CPythonInvoker(36, /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py): start processing
18:39:16 T:139843242784512   DEBUG: -->Python Interpreter Initialized<--
18:39:16 T:139843242784512   DEBUG: CPythonInvoker(36, /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py): the source file to load is "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py"
18:39:16 T:139843242784512   DEBUG: CPythonInvoker(36, /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py): setting the Python path to /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0:/usr/lib/python2.7/site-packages/wx-3.0-gtk2
18:39:16 T:139843242784512   DEBUG: CPythonInvoker(36, /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py): entering source directory /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher
18:39:16 T:139843242784512   DEBUG: CPythonInvoker(36, /home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py): instantiating addon using automatically obtained id of "plugin.program.advanced.emulator.launcher" dependent on version 2.24.0 of the xbmc.python api
18:39:16 T:139843252225792   DEBUG: Thread scriptobs start, auto delete: false
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: ---------- Called AEL addon.py Main() constructor ----------
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: 2.7.11 (default, Mar 31 2016, 06:18:34) [GCC 5.3.0]
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: __addon_id__   plugin.program.advanced.emulator.launcher
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: __version__    0.9.0
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: __profile__    special://profile/addon_data/plugin.program.advanced.emulator.launcher/
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: sys.argv[0] = "plugin://plugin.program.advanced.emulator.launcher/"
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: sys.argv[1] = "11"
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: sys.argv[2] = "?com=LAUNCH_ROM&catID=fca2b6b98f5b18a31da7de324feb5a22&launID=512cc5146b36e0561efa0e11dc94c4a4&romID=f7d5000374ca4bfdb3c6d8686ce4b4cc"
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: args = {'romID': ['f7d5000374ca4bfdb3c6d8686ce4b4cc'], 'launID': ['512cc5146b36e0561efa0e11dc94c4a4'], 'com': ['LAUNCH_ROM'], 'catID': ['fca2b6b98f5b18a31da7de324feb5a22']}
18:39:16 T:139843242784512   DEBUG: AEL DEBUG: content_type = None
18:39:16 T:139843242784512   DEBUG: AEL VERB : fs_load_catfile() Loading /home/mac/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/categories.xml
18:39:16 T:139843242784512   DEBUG: AEL VERB : Loaded metadata scraper  TheGamesDB
18:39:16 T:139843242784512   DEBUG: AEL VERB : Loaded thumb scraper     TheGamesDB
18:39:16 T:139843242784512   DEBUG: AEL VERB : Loaded fanart scraper    TheGamesDB
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() Launching ROM in Launcher...
18:39:16 T:139843242784512   DEBUG: AEL VERB : fs_load_ROMs_JSON() Loading JSON file /home/mac/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/ROMs/roms_Emulation_GameCube_512cc5.json
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() categoryID  = fca2b6b98f5b18a31da7de324feb5a22
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() launcherID  = 512cc5146b36e0561efa0e11dc94c4a4
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() romID       = f7d5000374ca4bfdb3c6d8686ce4b4cc
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() application = "/usr/bin/dolphin-emu-cli"
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() apppath     = "/usr/bin"
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() romfile     = "/home/mac/Jeux/Roms/Gamecube/Legend of Zelda, The - Twilight Princess (Europe) (En,Fr,De,Es,It).gcz"
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() rompath     = "/home/mac/Jeux/Roms/Gamecube"
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() rombasename = "Legend of Zelda, The - Twilight Princess (Europe) (En,Fr,De,Es,It).gcz"
18:39:16 T:139843242784512   DEBUG: AEL INFO : _command_run_rom() arguments   = ""/home/mac/Jeux/Roms/Gamecube/Legend of Zelda, The - Twilight Princess (Europe) (En,Fr,De,Es,It).gcz""
18:39:16 T:139843242784512   DEBUG: AEL VERB : _run_before_execution() media_state is "Pause" (1)
18:39:16 T:139843242784512   DEBUG: AEL VERB : _run_before_execution() Toggling Kodi fullscreen DEACTIVATED in Launcher
18:39:16 T:139843242784512   DEBUG: AEL VERB : _run_before_execution() Calling xbmc.enableNavSounds(False)
18:39:16 T:139846176577280   DEBUG: PulseAudio: Stream ready
18:39:16 T:139846176577280  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
18:39:16 T:139846176577280   DEBUG: CActiveAESink::OpenSink - PULSE Initialized:
18:39:16 T:139846176577280   DEBUG:   Output Device : Default
18:39:16 T:139846176577280   DEBUG:   Sample Rate   : 44100
18:39:16 T:139846176577280   DEBUG:   Sample Format : AE_FMT_FLOAT
18:39:16 T:139846176577280   DEBUG:   Channel Count : 2
18:39:16 T:139846176577280   DEBUG:   Channel Layout: FL,FR
18:39:16 T:139846176577280   DEBUG:   Frames        : 2205
18:39:16 T:139846176577280   DEBUG:   Frame Size    : 8
18:39:16 T:139846187149056   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
18:39:16 T:139846201382976   DEBUG: Previous line repeats 1 times.
18:39:16 T:139846201382976   DEBUG: ------ Window Init (DialogBusy.xml) ------
18:39:16 T:139846201382976   DEBUG: Window DialogBusy.xml was already loaded
18:39:16 T:139846201382976   DEBUG: Alloc resources: 0.01ms
18:39:16 T:139846201382976   DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.
18:39:16 T:139846201382976   DEBUG: Previous line repeats 20 times.
18:39:16 T:139846201382976    INFO: LIRC SetEnabled: disabled
18:39:16 T:139846201382976   DEBUG: CSettingsManager: requested setting (pvrmanager.enabled) was not found.
`

**Comment by eggfoo** [comment]
I'll test these fixes in 1 week when I return from vacation/holiday. On my Windows 7 machines.

**Comment by Wintermute0110** [comment]
Please try now. Both #9 and #10 should be fixed now for standalone and emulator launchers.

**Comment by mac1202** [comment]
Issue still present even with the 4b7028e5bc370682eb7d368a03287b798c6a16b7 commit.
I m using latest krypton git version maybe is the cause of the problem.

**Comment by Wintermute0110** [comment]
OK, that's explain some things. I use Jarvis for both development and testing. It is difficult to me to try Kypton because I'm running Linux Debian and until Krypton is not packaged I would have to compile. Krypton will create more problems that I would like (for example, with context menus) and this could be another one (or even a bug in Krypton itself).

I think best course of action is to wait a bit until Krypton is released and then I will tackle all the problems with the transition Jarvis/Krypton.

If you find any other bug or unexpected behaviour please report it. Keep in mind I will do quite a lot of changes in the following weeks (I will increase the supported artwork types) and there could be broken things for a time.

**Comment by Wintermute0110** [comment]
Is this issue still affecting AEL? Should it close it?

**Comment by mac1202** [comment]
Just tested and it work properly now
